# Generated by Django 3.2.5 on 2021-07-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoMe', '0002_auto_20210711_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
