# Generated by Django 3.2.5 on 2021-07-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoMe', '0003_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Date_create',
            field=models.DateField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Date_end',
            field=models.DateField(verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Date_update',
            field=models.DateField(verbose_name='Последнее обновление'),
        ),
    ]
