# Generated by Django 3.2.5 on 2021-07-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoMe', '0004_auto_20210718_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Date_create',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
